init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"YourTestDll -noshadow" -output:"coverage.xml" -filter:"+[YourSUTNamepace*]* -[YourTestNamespace*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t bd942bc0-a8a8-46b7-b4b2-cbd3273159d3
artifacts:
  - path: '**\*.nupkg'
deploy: off
os: Visual Studio 2017